name: PR / Sources

on:
  pull_request:
    branches: [main]

jobs:
  validate-sources:
    name: Validate sources
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: yarn
      - run: yarn install --frozen-lockfile
      - run: yarn next lint
      - run: yarn prettier --check .
      - run: yarn cspell --no-must-find-files '**'
